# Generated by Django 2.1.15 on 2021-03-07 04:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='userFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('uploadDate', models.DateTimeField(default=datetime.datetime(2021, 3, 7, 4, 41, 24, 283666, tzinfo=utc))),
                ('realFile', models.FileField(upload_to='files/')),
                ('permissionToDownload', models.CharField(choices=[('Yes', 'Allow'), ('No', 'Disallow')], default='Yes', max_length=3)),
                ('permissionToSeeUser', models.CharField(choices=[('Yes', 'Allow'), ('No', 'Disallow')], default='Yes', max_length=3)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
