# Generated by Django 3.1.7 on 2021-03-10 15:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210309_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='uploadDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 10, 15, 46, 29, 793094, tzinfo=utc)),
        ),
    ]
