# Generated by Django 3.1 on 2021-03-13 03:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210310_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='FileType',
            field=models.CharField(choices=[('Text', 'Text'), ('Image', 'Image'), ('Video', 'Video'), ('Audio', 'Audio')], default='Random', max_length=5),
        ),
        migrations.AlterField(
            model_name='userfile',
            name='uploadDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 13, 3, 21, 24, 293302, tzinfo=utc)),
        ),
    ]
