# Generated by Django 2.1.15 on 2021-03-18 16:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20210318_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='uploadDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 18, 16, 59, 49, 821572, tzinfo=utc)),
        ),
    ]
