# Generated by Django 2.1.15 on 2021-03-07 04:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0003_auto_20210304_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 7, 4, 41, 24, 284661, tzinfo=utc)),
        ),
    ]
