# Generated by Django 3.1 on 2021-03-13 03:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0007_auto_20210310_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 13, 3, 21, 24, 294299, tzinfo=utc)),
        ),
    ]
