# Generated by Django 2.1.15 on 2021-03-18 17:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0020_auto_20210318_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 18, 17, 58, 39, 429249, tzinfo=utc)),
        ),
    ]
